create table EMPLOYEE_DATA (
	employee_id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	street_address VARCHAR(50),
	phone_number VARCHAR(50)
);
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (1, 'Gabbie', 'MacConnel', '3 Carioca Road', '951-164-2841');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (2, 'Shea', 'Priestland', '8 Fordem Terrace', '735-649-7588');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (3, 'Nealy', 'Andino', '76 Canary Junction', null);
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (4, 'Ethelbert', 'Springell', '4 Anderson Drive', '799-904-5587');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (5, 'Susann', 'Godley', '4188 Bunting Pass', null);
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (6, 'Kally', 'Kearey', '787 Shelley Junction', '772-897-7947');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (7, 'Freeland', 'Ferriere', '981 Briar Crest Crossing', '276-947-1704');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (8, 'Brandi', 'Shallcroff', '3314 Main Trail', '176-142-7778');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (9, 'Dorey', 'Haggarty', '1 Toban Pass', '573-534-3840');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (10, 'Elisha', 'Harnwell', '7695 Gerald Road', '724-993-4707');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (11, 'Roley', 'Molan', '81707 Cambridge Plaza', '188-240-3381');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (12, 'Pierette', 'Romaint', '27 Prairieview Avenue', '503-650-6395');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (13, 'Ardisj', 'Defont', '041 La Follette Place', '528-956-0323');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (14, 'Nollie', 'De Lascy', '66997 Montana Way', '646-144-3147');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (15, 'Francis', 'Blackwood', '8 Fisk Avenue', '955-692-2038');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (16, 'Zachery', 'Edensor', '0 Harper Junction', '656-762-9285');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (17, 'Elsey', 'Llewelly', '59436 Mccormick Alley', '499-949-1356');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (18, 'Simeon', 'Murrish', '44629 Green Ridge Pass', '412-153-4247');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (19, 'Urbain', 'Upson', '498 Westridge Hill', '746-762-9562');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (20, 'Cordie', 'Zanioletti', '32 Southridge Road', '491-427-8947');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (21, 'Gordon', 'Tolefree', '6163 Morrow Plaza', '249-300-5494');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (22, 'Ingamar', 'Millea', '9 Comanche Park', '543-877-6496');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (23, 'Barry', 'Cridge', '38438 Bartelt Park', '926-331-7594');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (24, 'Lyman', 'Jolliman', '0 Mayer Road', '153-124-6934');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (25, 'Maurita', 'Crouch', '89 Reinke Place', null);
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (26, 'Joya', 'Pirrey', '998 Golf View Court', '718-389-9834');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (27, 'Vassili', 'Clampin', '326 Shopko Avenue', '349-782-5253');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (28, 'Blayne', 'Engall', '3621 Bunker Hill Place', '304-152-5630');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (29, 'Roseline', 'Carruthers', '460 Mendota Lane', '926-258-3283');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (30, 'Lenci', 'Knocker', '44 Crownhardt Court', '406-233-3360');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (31, 'Arly', 'Duffill', '51 Loeprich Terrace', '691-910-5972');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (32, 'Caria', 'Ayscough', '6490 Village Road', '459-665-8583');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (33, 'Ninetta', 'Mauro', '77 Mosinee Point', null);
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (34, 'Parry', 'Woolard', '443 Barnett Circle', '471-914-0548');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (35, 'Dilly', 'Angless', '50151 Northview Park', '700-970-9579');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (36, 'Brander', 'Jakaway', '52629 West Road', '632-615-4449');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (37, 'Rosie', 'Brymham', '29750 Dottie Point', '561-577-7983');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (38, 'Hyman', 'Pyson', '76769 4th Road', '586-301-9527');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (39, 'Querida', 'Ninnotti', '37245 Hansons Plaza', '811-655-8778');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (40, 'Concordia', 'Newarte', '484 School Court', '293-629-2334');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (41, 'Deloris', 'Phelipeau', '179 Fairview Alley', '718-538-8327');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (42, 'Aarika', 'Meese', '810 Farwell Way', '775-988-1946');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (43, 'Travis', 'Eaden', '96 Gulseth Plaza', '559-343-1720');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (44, 'Lanny', 'Raoult', '4 Warbler Street', null);
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (45, 'Billye', 'Bernette', '50 Longview Pass', '365-698-3422');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (46, 'Gwynne', 'Kleinmann', '082 Coolidge Terrace', '977-268-8384');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (47, 'Florencia', 'Blum', '34458 Bunker Hill Lane', '160-566-4362');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (48, 'Michelle', 'Lawly', '926 Golden Leaf Drive', '758-356-3911');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (49, 'Brion', 'Klawi', '69225 Almo Point', '560-242-6117');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (50, 'Si', 'Braganca', '1315 Jay Alley', '864-666-1932');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (51, 'Quinn', 'Ingon', '2920 Blackbird Place', '591-298-2765');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (52, 'Jeanine', 'Meade', '4147 Rusk Court', '565-923-0703');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (53, 'Suzie', 'Babb', '21752 Arrowood Plaza', '666-895-9930');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (54, 'Pete', 'Giorgio', '69 Bunker Hill Junction', '104-471-9069');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (55, 'Paulita', 'McVanamy', '4696 Butternut Hill', null);
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (56, 'Jenni', 'Scirman', '79 Mayfield Way', '407-934-0517');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (57, 'Ripley', 'Murfill', '4908 Jenifer Hill', '707-124-0356');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (58, 'Rozina', 'Soigne', '14 Golf Course Way', '954-316-3001');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (59, 'Eyde', 'Pinke', '9149 Gale Way', null);
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (60, 'Stan', 'Picknett', '83 Leroy Terrace', '385-763-1830');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (61, 'Willi', 'Lambis', '188 Hudson Alley', '878-321-9869');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (62, 'Ula', 'Hesse', '08 Reindahl Road', '784-736-7208');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (63, 'Sidney', 'Leckey', '98 Elmside Crossing', null);
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (64, 'Dode', 'Vearncomb', '686 Moulton Trail', '341-173-0548');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (65, 'Hollyanne', 'Prin', '011 Bartillon Avenue', '153-734-2017');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (66, 'Vale', 'Deppe', '2775 Monica Avenue', '867-368-6151');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (67, 'Con', 'Ridoutt', '88438 Lindbergh Crossing', '351-449-3934');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (68, 'Hilliard', 'Hawford', '901 Vidon Point', '833-984-4774');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (69, 'Mella', 'Hartshorne', '7407 Eastwood Way', null);
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (70, 'Renelle', 'Tribe', '9364 Esch Junction', null);
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (71, 'Brit', 'Tarren', '3 Brown Drive', '551-457-0796');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (72, 'Nicolis', 'Glasspool', '74625 Jackson Street', '954-353-4326');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (73, 'Aldric', 'Barthram', '4 Bunting Parkway', '316-125-5203');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (74, 'Donnell', 'Goddert.sf', '65 Nobel Point', '420-772-3989');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (75, 'Allison', 'Levet', '6762 Kropf Circle', '406-388-3190');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (76, 'Timoteo', 'De Bruyn', '3 Dakota Road', '647-999-3628');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (77, 'Rad', 'Jankowski', '75 Kropf Park', '948-156-4665');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (78, 'Herold', 'Extal', '7815 Judy Point', '204-892-0899');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (79, 'Tymothy', 'Klewer', '0439 Mayfield Crossing', '539-924-2619');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (80, 'Demetri', 'Hollow', '78340 Sugar Point', '647-817-0777');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (81, 'Otho', 'Dartnall', '1 Hagan Avenue', '641-547-7684');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (82, 'Hetti', 'Zanassi', '5517 Reindahl Avenue', null);
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (83, 'Aluin', 'Hindes', '1843 Vera Lane', null);
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (84, 'Gerrilee', 'Shird', '30266 Oneill Street', '223-354-8671');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (85, 'Janka', 'Sammons', '39958 Elka Road', '959-950-3850');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (86, 'Nels', 'Worsnop', '964 Carpenter Drive', '623-681-8547');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (87, 'Ambrosio', 'Ert', '31 Gina Crossing', '321-848-5461');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (88, 'Erin', 'Mazonowicz', '3241 Moose Crossing', '190-917-4873');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (89, 'Welch', 'Caston', '0 Gina Drive', '880-917-6718');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (90, 'Leora', 'Merredy', '4411 Sloan Circle', '584-706-4821');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (91, 'Inga', 'Chaster', '028 Starling Parkway', '718-257-3217');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (92, 'Hyacinthia', 'Morin', '65 Londonderry Park', '466-652-1727');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (93, 'Marlin', 'Ashfold', '9 Sage Alley', '253-186-6252');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (94, 'Thor', 'Gorick', '85153 Rowland Drive', '885-610-1167');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (95, 'Shannan', 'Pymer', '9 Green Junction', '854-660-4709');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (96, 'Martin', 'Eakin', '4 Bluestem Street', '856-307-9038');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (97, 'Tommy', 'Layson', '39 Jay Avenue', '806-747-1375');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (98, 'Norbie', 'Pollicott', '7508 Cherokee Plaza', '890-768-8600');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (99, 'Jimmie', 'Wolfenden', '9044 Jackson Court', '519-137-7825');
insert into EMPLOYEE_DATA (employee_id, first_name, last_name, street_address, phone_number) values (100, 'Ronnie', 'McKeney', '146 Packers Road', null);
