create table PATIENT_DATA (
	patient_id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	street_address VARCHAR(50),
	phone_number VARCHAR(50),
	therapy_category VARCHAR(9),
	drug_name VARCHAR(50)
);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (1, 'Benjie', 'Scoggans', '02 Prairie Rose Hill', '402-160-1908', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (2, 'Malinde', 'Ellicock', '10837 Myrtle Trail', '656-595-1318', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (3, 'Hedvige', 'Goodings', '4726 Steensland Avenue', '801-426-0146', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (4, 'Rowena', 'Stopher', '84 Tennessee Alley', '529-181-5513', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (5, 'Barbie', 'Zellmer', '1078 Mallory Center', '349-455-5259', 'Therapy 2', 'sodium sulfacetamide, sulfur');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (6, 'Moria', 'Whitehurst', '22133 Comanche Road', null, 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (7, 'Rees', 'Tregiddo', '7 Forest Dale Junction', '737-195-3288', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (8, 'Malanie', 'Kinchin', '22 Toban Plaza', '722-111-8101', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (9, 'Gareth', 'Reavey', '86 Fulton Junction', '517-928-2206', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (10, 'Kalindi', 'Boij', '210 Summerview Way', '172-936-6112', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (11, 'Katha', 'Bricket', '8049 Continental Court', '742-534-8421', 'Therapy 2', 'Avobenzone, Octinoxate, Octisalate, Oxybenzone');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (12, 'Jocko', 'Biddulph', '96 Pearson Hill', '500-583-5529', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (13, 'Emili', 'Rauprich', '38 Sloan Road', '194-131-7072', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (14, 'Bard', 'Yakubovics', '03743 Montana Point', '565-473-5293', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (15, 'Yorgo', 'Benezet', '48681 Bultman Plaza', '871-264-2191', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (16, 'Chrysler', 'MacGinney', '4 Lawn Point', '791-485-0772', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (17, 'Aile', 'Lardner', '0504 Sundown Park', '437-537-6214', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (18, 'Emmy', 'Bramelt', '12 Kropf Street', '697-688-3799', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (19, 'Gilbertina', 'Rabier', '2595 Lunder Lane', '903-451-4556', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (20, 'Brendon', 'O''Geneay', '95789 Charing Cross Hill', '998-499-3619', 'Therapy 2', 'Verapamil Hydrochloride');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (21, 'Eddy', 'Grayston', '89 Schiller Way', '268-148-9650', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (22, 'Ruthann', 'Hughs', '72 Florence Plaza', '807-201-0266', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (23, 'Griswold', 'MacQuist', '34 Myrtle Hill', '912-348-8468', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (24, 'Mavra', 'Polino', '52550 Manley Street', null, 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (25, 'Milton', 'Standing', '235 Judy Street', '472-614-6895', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (26, 'Neal', 'De''Ath', '8681 Clarendon Parkway', null, 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (27, 'Web', 'Ray', '863 Spenser Way', '716-807-8927', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (28, 'Izaak', 'Whicher', '24 Bluestem Plaza', '430-193-7479', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (29, 'Kenton', 'Collidge', '55769 Cambridge Lane', '327-968-8375', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (30, 'Lisa', 'Wildman', '84 Manley Place', '331-375-7730', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (31, 'Lancelot', 'Dennidge', '447 Hayes Alley', '303-795-1407', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (32, 'Pamella', 'Arnefield', '8843 Stang Way', '647-741-7864', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (33, 'Marcelle', 'Neath', '1349 Riverside Circle', '986-959-0100', 'Therapy 3', 'Methylphenidate Hydrochloride');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (34, 'Sutton', 'Bowyer', '63152 Sutteridge Way', '580-168-0797', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (35, 'Adel', 'Glanfield', '56 Ohio Alley', '169-390-9051', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (36, 'Tirrell', 'Baine', '8 Helena Pass', '243-462-3528', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (37, 'Cameron', 'Willmot', '24 Roxbury Court', '454-730-3676', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (38, 'Randene', 'Felkin', '62 Waxwing Place', '461-821-2833', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (39, 'Delphine', 'Button', '95 Artisan Hill', '512-911-9450', 'Therapy 2', 'Calgest');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (40, 'Adelina', 'Rulten', '668 Mifflin Parkway', '760-175-1737', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (41, 'Emma', 'Braybrookes', '79361 Jackson Parkway', '543-607-5212', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (42, 'Orville', 'Elford', '56 Westport Alley', '346-116-0464', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (43, 'Skippie', 'Paslow', '10 Chive Center', null, 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (44, 'Jamaal', 'Kenna', '0 Hagan Lane', '211-811-3854', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (45, 'Jany', 'Jorissen', '3929 Amoth Drive', '434-332-4193', 'Therapy 2', 'Miconazole nitrate');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (46, 'Netta', 'Swyn', '0678 Algoma Circle', '134-308-6215', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (47, 'Camella', 'Coldrick', '842 Artisan Court', '895-111-3897', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (48, 'Tremain', 'Bridgett', '0 Ohio Drive', '745-849-6055', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (49, 'Allin', 'Gatenby', '1250 Old Gate Alley', '937-148-0235', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (50, 'Nona', 'Baradel', '6760 Kim Terrace', '591-422-5418', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (51, 'Philippine', 'Floweth', '5253 Dwight Park', '650-670-0305', 'Therapy 1', 'Johnson Grass Sorghum halepense');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (52, 'Atalanta', 'Melonby', '9854 Emmet Street', null, 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (53, 'Randi', 'Tomadoni', '92 Bunting Court', '213-838-8174', 'Therapy 2', 'Oxytocin');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (54, 'Crysta', 'MacNeely', '3 New Castle Way', '621-379-9628', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (55, 'Devonna', 'Peetermann', '9 Chive Alley', '550-362-0843', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (56, 'Tamqrah', 'Filyushkin', '0 Bowman Place', '388-712-0869', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (57, 'Afton', 'Stooke', '38 Vahlen Parkway', '434-290-3644', 'Therapy 1', 'Naproxen Sodium');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (58, 'Malachi', 'McMillam', '3 Helena Court', '564-300-2859', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (59, 'Chen', 'Ferrand', '7688 Pankratz Circle', '896-796-4492', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (60, 'Flynn', 'Collopy', '1095 Charing Cross Parkway', '725-495-2356', 'Therapy 2', 'Acetaminophen, Chlorpehniramine HCl, Dextromethorphan HBr, Phenylephrine HCl');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (61, 'Paulie', 'Andras', '4 Meadow Ridge Trail', '437-377-4856', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (62, 'Baillie', 'Lints', '455 Rusk Way', '845-254-0078', 'Therapy 2', 'amlodipine besylate and atorvastatin calcium');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (63, 'Jodie', 'Kentish', '878 Scoville Drive', '527-817-7029', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (64, 'Allyson', 'Dines', '21 Prentice Junction', null, 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (65, 'Kerwinn', 'Schwand', '12 Paget Circle', '659-685-9669', 'Therapy 2', 'gabapentin');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (66, 'Silvie', 'Peschmann', '054 Burrows Parkway', '255-328-4612', 'Therapy 3', 'Aluminum Chlorohydrate');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (67, 'Celka', 'Stredwick', '96156 Barby Trail', '441-923-9457', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (68, 'Jessalyn', 'Blazynski', '332 Loomis Street', null, 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (69, 'Gwendolyn', 'Besnardeau', '1 Northfield Plaza', '629-720-7098', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (70, 'Dedra', 'Pocknell', '92211 Beilfuss Center', '753-380-0299', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (71, 'Erinn', 'Stroban', '53571 Arrowood Lane', '673-487-3991', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (72, 'Mersey', 'Paddell', '5373 Manufacturers Alley', '110-819-9367', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (73, 'Edythe', 'Ruger', '72 Bartillon Crossing', '687-632-7444', 'Therapy 1', 'MENTHOL, METHYL SALICYLATE');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (74, 'Clarey', 'Fanner', '212 Melody Way', '840-141-7025', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (75, 'Rayshell', 'Pougher', '01 Talisman Avenue', '421-119-5014', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (76, 'Eli', 'Hewes', '8547 Lillian Crossing', '890-640-9738', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (77, 'Othilie', 'Woolens', '43 Oxford Way', '340-819-4884', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (78, 'Abbey', 'Greguol', '0911 Shelley Crossing', '499-482-8721', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (79, 'Othilia', 'Weale', '18949 Alpine Alley', '617-349-8930', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (80, 'Riobard', 'Scottesmoor', '837 Monterey Lane', '197-704-7658', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (81, 'Bevon', 'Alywin', '094 Oak Street', '502-705-7649', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (82, 'Linoel', 'Barbour', '75370 Nancy Crossing', '536-651-3307', 'Therapy 2', 'Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (83, 'Hirsch', 'Scarrott', '31181 Bunker Hill Alley', '878-830-2881', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (84, 'Ellwood', 'Tester', '010 Armistice Avenue', '129-870-8285', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (85, 'Ingar', 'Sepey', '50 Jana Hill', null, 'Therapy 3', 'Aluminum Chlorohydrate');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (86, 'Kordula', 'Dorkens', '22 Monica Hill', '550-427-5287', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (87, 'Casey', 'Pering', '29083 American Ash Crossing', '272-199-0929', 'Therapy 3', 'Medroxyprogesterone Acetate');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (88, 'Lisabeth', 'Greenwell', '94 Union Trail', '758-879-5627', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (89, 'Harriott', 'Kindon', '97 Kropf Avenue', null, 'Therapy 1', 'ARSENICUM ALBUM');
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (90, 'Lorinda', 'Bonhan', '16 Fair Oaks Parkway', '966-451-9071', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (91, 'Letty', 'Dunning', '55683 Mayfield Street', '268-675-3023', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (92, 'Evelyn', 'Bannell', '36 Summerview Parkway', null, 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (93, 'Elmer', 'Sanbroke', '54 Coolidge Junction', '745-792-5038', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (94, 'Humfrey', 'Laurencot', '5698 Straubel Place', null, 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (95, 'Anna-diana', 'Cantrell', '5067 Sundown Trail', '246-238-4546', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (96, 'Cherie', 'Toulson', '116 Westport Point', '888-174-9318', 'Therapy 2', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (97, 'Kayley', 'Mapis', '74 Prairie Rose Road', '847-565-1608', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (98, 'Ingemar', 'Wain', '0707 Kensington Center', '947-605-6737', 'Therapy 3', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (99, 'Rodrique', 'Hinksen', '57 Mayer Circle', '735-311-5574', 'Therapy 1', null);
insert into PATIENT_DATA (patient_id, first_name, last_name, street_address, phone_number, therapy_category, drug_name) values (100, 'Blondelle', 'Cominello', '16 Eastwood Plaza', '693-827-2416', 'Therapy 1', null);
